### ISSUE TITLE
Remove FAKE_ACKERMANN

### ISSUE THREAD

**Issue by maxehrhardt** [esa-prl/ExoMy_Software#23]
This locomotion mode is not used and should be removed.

**Comment by diogopbrandao** [comment]
Not to be removed, locomotion mode might be useful.
Need to assign button (remove `pass`) on the joystick_parser_node

**Comment by 0xD0M1M0** [comment]
I wonder in which configuration this locomotion mode is "useful". As a regular Exomy driver using the web interface or the joystick it is not useful to drive in this mode. It looks strange, drives funky and there is an "real" Ackermann with a better performance existing. Why keeping this code? Even for debugging I don't see any need. What kind of debugging should that be?

**Comment by 0xD0M1M0** [comment]
Closed. Fake Ackermann is considered a useful feature by ESA PRL.

To activate this feature with the "Logitech F710 joystick", search for 
`# B Button
    if (data.buttons[2] == 1):`
in `src/joystick_parser_node.py` and replace
`pass` 
by
`locomotion_mode = LocomotionMode.FAKE_ACKERMANN.value`

Now button "B" enables the Fake Ackermann.
