### ISSUE TITLE
Error with run_exomy.sh

### ISSUE THREAD

**Issue by ghost** [esa-prl/ExoMy_Software#26]
the script does a thousend things, at the end I get
RLException: error loading <rosparam> tag:
  file does not exist [/root/exomy_ws/src/exomy/config/exomy.yaml]

**Comment by 0xD0M1M0** [comment]
Hello,
it is kind of very generic question and request. In which mode is run_exomy.sh run? Is the docker setup correctly? Did you run the configuration scripts?

The file exomy.yaml is created by the script "config_motor_pins.py". How to run this script is described in the wiki: https://github.com/esa-prl/ExoMy/wiki/Final-Integration
in chapter "Configure Motor Mapping". For best performance and correct functionallity, please also run "Calibrate Driving Motors" and "Calibrate Steering Motors.

For further instructions on the docker container, you can read:
https://github.com/esa-prl/ExoMy/wiki/Software-Instructions

**Comment by ghost** [comment]
Thanks, it was just an error message after running the -c option of the run_exomy.sh script. 
I manually copied the template to exomy.yaml to circumvent the message.
However, after finishing the calibration stuff I had some trouble finding the hint for the -a option of the script. So I experienced an initial lockdown with the logitec controller. Its all well now, thanks.
